name: {{cookiecutter.repo_name}}
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyter_contrib_nbextensions
  - jupyter
  - pep8
  - matplotlib
  - pandas
  - numpy
  - isort
  - flake8
  - black
  - scikit-learn
  - pickle5
  - deon