name: {{cookiecutter.repo_name}}
channels:
  - conda-forge
  - defaults
dependencies:
  #- python = 3.8
  - jupyter
  - jupyter_contrib_nbextensions
  - numpy
  - pandas
  - matplotlib
  - isort
  - black
  - flake8
  - click
  - pytest
  - scikit-learn
  - pickle5
  - importlib
  - deon
  - pip 